language: python
python:
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
- pip install requests
script:
- python3 TestDataBase.py
- python3 TestAPIExtra.py
- python3 TestAPIGoogle.py
